name: dart_emu_example
description: Flutter terminal UI for the dart_emu RISC-V emulator.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  archive: ^4.0.0
  dart_emu:
    path: ../
  desktop_drop: ^0.5.0
  file_picker: ^9.0.0
  flutter:
    sdk: flutter
  xterm: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  shaders:
    - shaders/crt.frag
  assets:
    - assets/
